- name: Deploy nginx site configuration
  template: src=mysite.j2 dest="/etc/nginx/conf.d/mysite.conf"
  notify: restart nginx
  tags: configuration

- name: Remove defaults
  file: path="/etc/nginx/conf.d/default.conf" state=absent
  tags: configuration

- name: ensure nginx is started
  service:
    name: nginx
    state: started
  tags: always