- hosts: webservers
  become: yes
  roles:
    - common
    - httpd
  tags:
    web  

- hosts: proxy
  become: yes
  roles:
    - common
    - nginx
  tags:
    proxy

- hosts: database
  become: yes
  roles:
    - common
    - mysql
  tags: database